[package]
name = "fhe_dksap"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
secp256k1 = { version = "0.31.1", features = ["alloc", "std", "rand"] }
sha3 = "0.10.8"
tfhe = { version = "*", features = ["boolean", "shortint", "integer"] }
